// FIRST EPSS daily exploitation probability predictions, not observed attacks.
// https://api.first.org/epss/ — bounded lookup/filter queries, no catalog pagination.
import { safeFetch } from '../utils/fetch.mjs';
import { providerTime, freshness, freshResult, unavailableResult } from '../utils/freshness.mjs';

const SOURCE = 'FIRST-EPSS';
const MAX_AGE = 48 * 3600000;
const CACHE_MS = 60 * 60000;
const cache = new Map();
const REQUEST = Object.freeze({ timeout: 10000, retries: 0, maxBytes: 2 * 1024 * 1024 });
const ATTRIBUTION = 'EPSS by FIRST.org; scores generated by Empirical Security';
const SUMMARY = 'EPSS estimates the probability of observed exploitation in the next 30 days. It is a prediction, and a low score does not supersede known exploitation or a CISA KEV listing.';

function cve(value) {
  return typeof value === 'string' && value.length <= 40 && /^CVE-\d{4}-\d{4,}$/.test(value) ? value : null;
}

function probability(value) {
  if (typeof value !== 'number' && !(typeof value === 'string' && /^(?:0(?:\.\d+)?|1(?:\.0+)?)$/.test(value))) return null;
  const number = Number(value);
  return Number.isFinite(number) && number >= 0 && number <= 1 ? number : null;
}

export function parseEpss(payload, { now = Date.now() } = {}) {
  const extras = { attribution: ATTRIBUTION, summary: SUMMARY, selection: 'Daily EPSS score snapshot' };
  if (payload?.error) return unavailableResult(SOURCE, payload.error, extras, now);
  if (!payload || payload.status !== 'OK' || (payload['status-code'] !== undefined && payload['status-code'] !== 200)) return unavailableResult(SOURCE, 'FIRST EPSS returned an unsuccessful response', extras, now);
  const observations = (Array.isArray(payload.data) ? payload.data : []).slice(0, 100).flatMap(row => {
    const identifier = cve(row?.cve); const epss = probability(row?.epss); const percentile = probability(row?.percentile);
    if (!identifier || epss === null || percentile === null) return [];
    // The CVE year and optional creation date are not the daily prediction date.
    const observedAt = providerTime(row.date);
    const scoreDate = observedAt?.slice(0, 10) || 'unknown';
    return [{ providerId: `${identifier}:${scoreDate}`, cve: identifier,
      title: `${identifier} exploitation prediction`,
      summary: `EPSS predicted exploitation probability over the next 30 days: ${(epss * 100).toFixed(3)}%; percentile ${(percentile * 100).toFixed(2)}. This score does not confirm an attack.`,
      source: SOURCE, url: `https://api.first.org/data/v1/epss?${new URLSearchParams({ cve: identifier, ...(observedAt ? { date: scoreDate } : {}) })}`,
      observedAt, publishedAt: observedAt, kind: 'cyber', severity: 'info',
      epss, percentile, predictionWindowDays: 30, exploitationConfirmed: false,
    }];
  });
  const dates = observations.map(row => row.observedAt).filter(Boolean).sort();
  const freshDates = dates.filter(date => freshness(date, MAX_AGE, now).fresh);
  // Empty results have no score date, even if a metadata date was supplied.
  const observedAt = freshDates.at(-1) || dates.at(-1) || null;
  const result = freshResult(SOURCE, observedAt, observations, extras, now);
  result.metrics = { scoreCount: result.observations.length, predictionWindowDays: 30,
    maxProbability: result.observations.length ? Math.max(...result.observations.map(row => row.epss)) : null };
  return result;
}

export async function briefing(options = {}) {
  const now = options.now ?? Date.now();
  const cves = options.cves === undefined ? null : Array.isArray(options.cves)
    ? [...new Set(options.cves.slice(0, 100).map(cve).filter(Boolean))].slice(0, 50) : [];
  const extras = { attribution: ATTRIBUTION, summary: SUMMARY };
  if (cves && !cves.length) return unavailableResult(SOURCE, 'No valid CVEs requested', extras, now);
  const query = new URLSearchParams(cves ? { cve: cves.join(','), limit: '50' } : { days: '7', limit: '20', order: '!epss' });
  if (cves && cves.join(',').length > 2000) return unavailableResult(SOURCE, 'CVE query exceeds the provider limit', extras, now);
  const key = query.toString();
  const fetcher = options.fetcher || safeFetch;
  const useCache = options.useCache ?? !options.fetcher;
  const previous = cache.get(key);
  let payload;
  if (useCache && previous?.fetcher === fetcher && now >= previous.collectedAt && now - previous.collectedAt < CACHE_MS) payload = previous.payload;
  else {
    try { payload = await fetcher(`https://api.first.org/data/v1/epss?${key}`, REQUEST); }
    catch { payload = { error: 'FIRST EPSS request failed' }; }
    if (useCache && !payload?.error && parseEpss(payload, { now }).status === 'ok') {
      if (cache.size >= 16 && !cache.has(key)) cache.delete(cache.keys().next().value);
      cache.set(key, { payload, fetcher, collectedAt: now });
    }
  }
  return { ...parseEpss(payload, { now }), selection: cves ? 'Daily predictions for requested CVEs' : 'Highest daily EPSS probabilities among CVEs first scored in the past 7 days' };
}
