"""Merge PWA copy without changing existing locale namespaces."""
import json
from pathlib import Path
COPY = {
'en': {'menu':'Install / offline','title':'Install and offline access','help':'Install from Chrome or Edge on localhost/HTTPS. The interface works offline; fresh collection and history search need the local server.','save':'Keep the last snapshot on this browser','privacy':'Off by default. Enabling stores the displayed intelligence on this browser until you clear it. Clearing also disables further saves.','saved':'Snapshot saved locally','empty':'No local snapshot saved.','clear':'Delete local snapshot','cleared':'Local snapshot deleted; further saves disabled.','install':'Install app','installHelp':'Use your browser’s Install app menu when available. First open this address online.','update':'Apply downloaded update','updateReady':'An update is downloaded. Apply it when you are ready.','noUpdate':'No downloaded update is waiting.','close':'Close','cached':'Saved snapshot · collection time','unknown':'Unknown time','storageError':'Local snapshot storage unavailable.','shellError':'Offline interface installation failed; reconnect and reload to retry.'},
'hu': {'menu':'Telepítés / offline','title':'Telepítés és offline használat','help':'Chrome-ban vagy Edge-ben, localhoston vagy HTTPS-en telepíthető. A felület offline is indul; az új adatgyűjtéshez és az előzmények kereséséhez szükséges a helyi szerver.','save':'Az utolsó pillanatkép mentése ebben a böngészőben','privacy':'Alapból kikapcsolt. Engedélyezéskor a megjelenített adatok ebben a böngészőben maradnak, amíg nem törlöd őket. A törlés a további mentést is kikapcsolja.','saved':'Helyi pillanatkép mentve','empty':'Nincs mentett helyi pillanatkép.','clear':'Helyi pillanatkép törlése','cleared':'A helyi pillanatkép törölve; a további mentés kikapcsolva.','install':'Alkalmazás telepítése','installHelp':'Ha elérhető, használd a böngésző Alkalmazás telepítése menüjét. Ezt a címet először online nyisd meg.','update':'Letöltött frissítés alkalmazása','updateReady':'Új frissítés letöltve. Akkor alkalmazd, amikor készen állsz.','noUpdate':'Nincs alkalmazásra váró letöltött frissítés.','close':'Bezárás','cached':'Mentett pillanatkép · gyűjtési idő','unknown':'Ismeretlen időpont','storageError':'A helyi pillanatkép nem menthető ebben a böngészőben.','shellError':'Az offline felület telepítése sikertelen; csatlakozz újra és töltsd újra az oldalt.'},
'fr': {'menu':'Installer / hors ligne','title':'Installation et accès hors ligne','help':'Installation avec Chrome ou Edge sur localhost/HTTPS. L’interface fonctionne hors ligne ; la collecte et la recherche dans l’historique nécessitent le serveur local.','save':'Conserver le dernier instantané dans ce navigateur','privacy':'Désactivé par défaut. Les données affichées restent dans ce navigateur jusqu’à leur suppression. La suppression désactive aussi les futures sauvegardes.','saved':'Instantané enregistré localement','empty':'Aucun instantané local enregistré.','clear':'Supprimer l’instantané local','cleared':'Instantané local supprimé ; futures sauvegardes désactivées.','install':'Installer l’application','installHelp':'Utilisez le menu d’installation du navigateur si disponible. Ouvrez d’abord cette adresse en ligne.','update':'Appliquer la mise à jour téléchargée','updateReady':'Une mise à jour est téléchargée. Appliquez-la lorsque vous êtes prêt.','noUpdate':'Aucune mise à jour téléchargée en attente.','close':'Fermer','cached':'Instantané enregistré · date de collecte','unknown':'Date inconnue','storageError':'Le stockage local de l’instantané est indisponible.','shellError':'L’installation hors ligne a échoué ; reconnectez-vous et rechargez la page.'}
}
root = Path(__file__).resolve().parents[1]
for language, copy in COPY.items():
    path = root / 'locales' / (language + '.json')
    data = json.loads(path.read_text(encoding='utf-8'))
    data['pwa'] = copy
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
